apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: actions-eks-cluster
  region: us-east-1

vpc:
  subnets:
    private:
      us-east-1a:
        id: subnet-0f6026e883c6cc7a0
      us-east-1b:
        id: subnet-0bd64d00b3de13bfa
  securityGroup: sg-0183a94535c7004be

nodeGroups:
  - name: actions-eks-ng
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 1
    maxSize: 2
    privateNetworking: true
