name: Pipeline
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            # checkout code
            - name: checkout code
              uses: actions/checkout@v4

            # Set up NodeJS
            - name: Set up NodeJS
              uses: actions/setup-node@v3
              with:
                node-version: 14

            # Install NodeJS Dependencies
            - name: Install NodeJS dependencies
              run: npm install
            # SonarQube Analysis
            - name: SonarQube Scan
              uses: SonarSource/sonarqube-scan-action@v4
              env:
                SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
                # Since the repository is public github token is not needed.

            # Build Docker Image
            - name: Build Docker images
              run: docker build -t $GITHUB_SHA .
            # Trivy Scan
            - name: Trivy Scan
              run: docker run -v /var/run/docker.sock:/var/run/docker.sock -v $HOME/Library/Caches:/root/.cache/ aquasec/trivy:latest image $GITHUB_SHA

            # # Create ECR  Repository
            - name: Create ECR
              run: aws ecr create-repository --repository-name action-ci-cd --region us-east-1
             


