name: Pipeline
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            # checkout code
            - name: checkout code
              uses: actions/checkout@v4

            # Set up NodeJS
            - name: Set up NodeJS
              uses: actions/setup-node@v3
              with:
                node-version: 14

            # Install NodeJS Dependencies
            - name: Install NodeJS dependencies
              run: npm install
            # SonarQube Analysis
            - name: SonarQube Scan
              uses: SonarSource/sonarqube-scan-action@v4
              env:
                SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
                # Since the repository is public github token is not needed.

            # Build Docker Image
            - name: Build Docker images
              run: docker build -t $GITHUB_SHA:latest .
            # Trivy Scan
            - name: Trivy Scan
              run: docker run -v /var/run/docker.sock:/var/run/docker.sock -v $HOME/Library/Caches:/root/.cache/ aquasec/trivy:latest image $GITHUB_SHA:latest

            # # Create ECR  Repository
            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v2
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
                aws-region: ${{ secrets.AWS_REGION}}
             ## Login to Amazon ECR   
            - name: Login to Amazon ECR
              run: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 871909687521.dkr.ecr.us-east-1.amazonaws.com
             
              # Create the ECR Repository (If Not Exists)
              
            - name: Create ECR Repository
              run:  |
                aws ecr describe-repositories --repository-names action-ci-cd --region us-east-1 || \
                aws ecr create-repository --repository-name action-ci-cd --region us-east-1
             
            # Tag and Push Image into ECR
            - name: Tag and Push Image into ECR
              run: |
                docker tag $GITHUB_SHA:latest 871909687521.dkr.ecr.us-east-1.amazonaws.com/action-ci-cd:latest
                docker push 871909687521.dkr.ecr.us-east-1.amazonaws.com/action-ci-cd:latest
                
            # Push the image Into Dockerhub Repository. The repository should be created manually
            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}


            - name: Build and push
              uses: docker/build-push-action@v4
              with:
                push: true
                tags: ${{ secrets.DOCKERHUB_USERNAME }}/action-cicd:${{ github.sha }}

            # We are going to do the continuous deployment
            # Creating ECS
            - name: Create for my image in ecr
              uses: bitovi/github-actions-deploy-ecs@v0.1.4
              id: ecs
              with:
                  aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws_default_region: us-east-1

                  #tf_stack_destroy: true # This is to destroy the stack
                  tf_state_bucket_destroy: true # Will only destroy the bucket if tf_stack_destroy is true

                  aws_ecs_task_cpu: 256
                  aws_ecs_task_mem: 512
                  aws_ecs_app_image: 871909687521.dkr.ecr.us-east-1.amazonaws.com/action-ci-cd:latest
                  aws_ecs_assign_public_ip: true

                  aws_ecs_container_port: 80
                  aws_ecs_lb_port: 8000
