name: GitHub Actions CI CD
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout Code
          uses: actions/checkout@v4