name: Pipeline
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            # checkout code
            - name: checkout code
              uses: actions/checkout@v4

            # Set up NodeJS
            - name: Set up NodeJS
              uses: actions/setup-node@v3
              with:
                node-version: 14

            # Install NodeJS Dependencies
            - name: Install NodeJS dependencies
              run: npm install
            # SonarQube Analysis
            - name: SonarQube Scan
              uses: SonarSource/sonarqube-scan-action@v4
              env:
                SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
                # Since the repository is public github token is not needed.

            # Build Docker Image
            - name: Build Docker images
              run: docker build -t $GITHUB_SHA .
            # Trivy Scan
            - name: Trivy Scan
              run: docker run -v /var/run/docker.sock:/var/run/docker.sock -v $HOME/Library/Caches:/root/.cache/ aquasec/trivy:latest image $GITHUB_SHA

            # # Create ECR  Repository
            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v2
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY_ID }}
                aws-region: ${{ secrets.AWS_REGION}}
             ## Login to Amazon ECR   
            - name: Login to Amazon ECR
              run: aws ecr get-login-password --region ${{ secrets.AWS_REGION}} | docker login --username AWS --password-stdin 871909687521.dkr.ecr.us-east-1.amazonaws.com
             
              # Create the ECR Repository (If Not Exists)

            - name: Create ECR Repository
              run:  |
                aws ecr describe-repositories --repository-names action-ci-cd --region us-east-1 || \
                aws ecr create-repository --repository-name action-ci-cd --region us-east-1
             


